language: python
python:
  - "3.5"
install:
  - pip install coveralls
  - pip install numpy scipy
  - pip install -r requirements.txt
script: coverage run --source=xanespy tests/test_frameset.py
after_success:
  - coveralls
