language: python
python:
  - "3.5"
install:
  - pip install coveralls
  - pip install numpy scipy
  - pip install -r requirements.txt
  - python setup.py install
script: coverage run test/tests.py
after_success:
  - coveralls
