language: python
python:
  - "3.5"
install:
  - pip install coveralls
  - pip install numpy scipy
  - pip install -r requirements.txt
  - echo $TRAVIS_BUILD_DIR
script: coverage run --source=xanespy test/tests.py
after_success:
  - coveralls
